import {
  blueButtonInteraction,
  buttonInteraction,
  disabledState,
  fieldInteraction,
  linkControlInteraction,
  noNativeOutline,
} from "./uno-interactions";

export const shortcuts = {
  "page-shell": "mx-auto w-full max-w-[1180px] px-4 py-6 pb-7 lt-md:px-2.5 lt-md:pt-3.5",
  "topbar-frame": "relative z-10 mx-auto flex h-[72px] w-full max-w-[1180px] items-center justify-between gap-4 px-4 lt-md:h-[66px] lt-md:gap-[13px] lt-md:px-[13px]",
  "topbar-brand": "inline-flex h-10 items-center gap-[6px] no-underline text-text transition-colors duration-200 hover:text-accent",
  "topbar-brand-mark": "h-10 w-10 shrink-0 object-contain transition-[filter] duration-200",
  "topbar-brand-copy": "text-[1.125rem] leading-none font-bold tracking-[0.02em] lt-sm:text-[1rem]",
  "topbar-actions": "flex shrink-0 items-center gap-4 lt-md:gap-[13px]",
  "round-link-control": linkControlInteraction,
  "hero-logo": "max-h-[140px] w-[min(560px,88vw)] object-contain transition-[filter] duration-200",
  "brand-logo-light": "filter-none",
  "brand-logo-dark": "filter invert hue-rotate-180",
  "ui-card": "my-4.5 rounded-2 border border-solid border-border bg-surface p-5.5 shadow-app lt-md:p-4",
  "round-control": `inline-flex h-10 w-10 cursor-pointer items-center justify-center rounded-full border border-solid border-control-border bg-control-bg p-0 text-text shadow-app ${buttonInteraction}`,
  "field-title": "mb-1.5 block font-[650]",
  "field-hint": "mt-1.25 block text-muted",
  "field-control": `h-[42px] min-h-[42px] w-full rounded-[10px] border border-solid border-control-border bg-control-bg px-3 py-2.5 text-text ${fieldInteraction} ${disabledState}`,
  "field-control-file": `h-[48px] min-h-[48px] w-full rounded-[10px] border border-solid border-control-border bg-control-bg px-2 py-[6px] leading-[32px] text-text ${fieldInteraction} ${disabledState}`,
  "field-select": "bg-no-repeat bg-[length:6px_6px] [background-image:linear-gradient(45deg,transparent_50%,var(--muted)_50%),linear-gradient(135deg,var(--muted)_50%,transparent_50%)] [background-position:calc(100%-18px)_50%,calc(100%-12px)_50%] pr-10",
  "help-button": `inline-flex h-5 w-5 cursor-pointer items-center justify-center rounded-full border border-solid border-control-border bg-surface-2 p-0 text-muted ${buttonInteraction}`,
  "help-button-icon": "h-3.5 w-3.5 shrink-0",
  "primary-action": `min-h-[42px] cursor-pointer rounded-2 border border-solid border-transparent bg-accent px-4 py-2.5 font-[750] text-accent-contrast ${blueButtonInteraction} ${disabledState}`,
  "secondary-action": `min-h-[42px] cursor-pointer rounded-2 border border-solid border-control-border bg-surface-2 px-4 py-2.5 text-text ${buttonInteraction} ${disabledState}`,
  "icon-action": `inline-flex h-[42px] min-h-[42px] w-11 items-center justify-center cursor-pointer rounded-2 border border-solid border-transparent bg-accent p-0 text-accent-contrast ${blueButtonInteraction} ${disabledState}`,
  "danger-icon-action": `inline-flex h-10 w-10 items-center justify-center cursor-pointer rounded-[10px] border border-solid border-control-border bg-surface-2 p-0 text-danger ${buttonInteraction} ${disabledState}`,
  "toggle-control": "inline-flex select-none items-center gap-3.5 text-text",
  "toggle-control-disabled": "text-muted",
  "toggle-copy": "text-[0.98rem] leading-[1.4]",
  "results-sort-button": `inline-flex w-full cursor-pointer items-center justify-between gap-2 rounded-[10px] border-none bg-transparent px-1 py-1 text-left text-inherit shadow-none [appearance:none] transition-colors duration-150 hover:text-text focus-visible:text-text focus-visible:shadow-control-glow ${noNativeOutline}`,
  "results-sort-icon": "inline-block h-4 w-4 shrink-0",
  "results-row-active": "[background-color:color-mix(in_srgb,var(--accent),transparent_90%)] transition-colors duration-150",
  "results-assign-button": `inline-flex h-8 w-8 min-h-[32px] cursor-pointer items-center justify-center rounded-[10px] border border-solid border-control-border bg-surface-2 p-0 text-text ${buttonInteraction} ${disabledState}`,
  "results-assign-button-active": `inline-flex h-8 w-8 min-h-[32px] cursor-pointer items-center justify-center rounded-[10px] border border-solid border-transparent bg-accent p-0 text-accent-contrast ${blueButtonInteraction} ${disabledState}`,
  "results-assign-icon": "h-[18px] w-[18px]",
  "table-head": "px-2 py-2 text-left text-[0.9rem] text-muted",
  "table-cell": "border-t border-border [border-top-style:solid] px-2 py-2 align-middle",
  "formula-table-head": "border-b border-border [border-bottom-style:solid] px-2 py-2 text-left text-[0.9rem] text-muted",
  "formula-table-cell": "px-2 py-2 align-middle",
  "chemical-formula": "whitespace-nowrap text-[0.95em]",
  "inline-code": "align-middle rounded-md border border-solid border-border bg-surface-2 px-1.5 py-0.5 font-mono text-[0.86em] text-text",
};
